### ISSUE TITLE
Update wiki to recommend Oracle JDK

### ISSUE THREAD

**Issue by bootstraponline** [sonyxperiadev/ApkAnalyser#1]
The [Trouble shooting](https://github.com/sonyericssondev/ApkAnalyser/wiki/Trouble-shooting) page recommends Sun Java which [has been removed](https://lists.ubuntu.com/archives/ubuntu-security-announce/2011-December/001528.html). The best way to run Java on Ubuntu is to download the JDK [from Oracle](http://www.oracle.com/technetwork/java/javase/downloads/index.html).

**Comment by sonyxperiadev** [comment]
Done, thanks for correction :)
